version: '3'

services:
  api:
    build: .
    command: ["flask", "run", "--host=0.0.0.0"]
    
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    build: ./demo-app-react-flask
    command: ["npm", "start"]
    
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api

